[package]
name = "solve"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
ctf = { local = "../ctf" }

[addresses]
solve =  "0x0"
sui =  "0000000000000000000000000000000000000002"

ctf = "0xc70f33fde08f8a8d1510f6c4dc21d2f8c458fe0a"
game = "0xc70f33fde08f8a8d1510f6c4dc21d2f8c458fe0a"
